# action.yml
name: 'Hello Universe!'
description: 'Greet the universe'
inputs:
  who-to-greet:  # id of input
    description: 'Who is greeting the universe'
    required: true
    default: 'Bob'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
